require("settings")
require("maps")
require("plugins")
vim.cmd("set ls=3")
vim.cmd("colorscheme nightfox")
vim.cmd("set fillchars=eob:\\ ")
vim.cmd([[highlight Normal guibg=#0c0c0c]])
vim.cmd([[highlight NormalFloat guibg=#0c0c0c]])
vim.cmd([[highlight WinSeparator guifg=#404040]])
vim.cmd([[autocmd User TelescopePreviewerLoaded setlocal number]])
