local g = vim.g
local o = vim.o
g.mapleader = " "
g.maplocalleader = " "
o.number = true
o.relativenumber = true
o.clipboard = "unnamedplus"
o.autoindent = true
o.showtabline = 0
o.expandtab = true
o.shiftwidth = 4
o.tabstop = 4
o.ruler = true
o.mouse = "a"
o.title = true
o.hidden = true
o.showmatch = true
o.inccommand = "split"
o.termguicolors = true
o.guicursor = "i:hor1"
o.pumheight = 10
